export const API_ENDPOINTS = {
  customerSupport: 'http://localhost:3002',
  modelRouter: 'https://model-router-sentinel-osa7fdp2fq-uc.a.run.app',
  multimodalQA: 'https://multimodal-qa-agent-osa7fdp2fq-uc.a.run.app',
  realEstate: 'https://real-estate-coordinator-osa7fdp2fq-uc.a.run.app',
  procurement: 'https://procurement-intelligence-agent-osa7fdp2fq-uc.a.run.app',
  redTeamer: 'https://agentic-red-teamer-osa7fdp2fq-uc.a.run.app',
  devrel: 'https://autonomous-devrel-agent-osa7fdp2fq-uc.a.run.app',
  cloudSecurity: 'https://cloud-security-sentinel-osa7fdp2fq-uc.a.run.app',
  complianceSanitizer: 'http://localhost:8001',
  fintechFraud: 'http://localhost:8081',
  medicalNurse: 'http://localhost:8002',
  revenueAuditor: 'http://localhost:8082',
  enterpriseSwarm: 'http://localhost:8004',
  multiAgentDebate: 'http://localhost:8005',
  featureAgent: 'http://localhost:3000',
  scientificSandbox: 'http://localhost:8501',
  serviceDispatch: 'http://localhost:3001',
  travelConcierge: 'http://localhost:8003',
};
